### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by migueldlr** [GTBitsOfGood/healthy-families-healthy-futures#50]
https://www.figma.com/file/6SnGmwXgJwpRojgPWXKkYn/Health-Families-Healthy-Futures-(HF)-%2F-Spr21?node-id=1766%3A5166

I drafted up a calendar layout for `EventCalendarSection.tsx`, but the design changed.

We also need to add a card that pops up when either the date or the event chip is clicked on: https://www.figma.com/file/6SnGmwXgJwpRojgPWXKkYn/Health-Families-Healthy-Futures-(HF)-%2F-Spr21?node-id=1770%3A5645

This task should also handle the mobile view!

**Comment by ibaniya98** [comment]
@migueldlr @97chaebin How do we want to display the info on the card if a given day has multiple events?

**Comment by 97chaebin** [comment]
@Juliazhu20 questions about displaying multiple events on card
